CREATE TABLE TTS_STUDENTS
(
STUDENT_ID NUMBER,
STUDENT_NAME VARCHAR2(30) NOT NULL,
STUDENT_PHNO NUMBER(10),
STUDENT_DOB DATE,
STUDENT_DOJ TIMESTAMP DEFAULT SYSTIMESTAMP,
STUDENT_GENDER CHAR(1),
STUDENT_EMAIL VARCHAR2(150),
STUDENT_ADDRESS LONG,
STUDENT_QUAL VARCHAR2(25),
STUDENT_PIC BLOB,
STUDENT_RESUME CLOB,
STUDENT_PROFILE BFILE,
CONSTRAINT STUDENT_ID_PK PRIMARY KEY(STUDENT_ID),
CONSTRAINT STUDENT_GENDER_CK CHECK (STUDENT_GENDER IN ('M','F'))
);

DROP TABLE TTS_STUDENTS;

CREATE TABLE TTS_STUDENT_DETAILS
(
DETAILS_ID NUMBER,
STUDENT_ID NUMBER,
COURSE_ID NUMBER,
TRAINER_ID NUMBER,
CONSTRAINT DETAILS_ID_PK PRIMARY KEY(DETAILS_ID),
CONSTRAINT STUDENT_ID_FK FOREIGN KEY(STUDENT_ID) REFERENCES TTS_STUDENTS(STUDENT_ID),
CONSTRAINT COURSE_ID_FK FOREIGN KEY(COURSE_ID) REFERENCES TTS_COURSES(COURSE_ID),
CONSTRAINT TRAINER_ID_FK FOREIGN KEY(TRAINER_ID) REFERENCES TTS_TRAINERS(TRAINER_ID)
); 

CREATE TABLE TTS_STUDENT_PAYMENTS
(
PAYMENT_ID NUMBER,
DETAIL_ID NUMBER,
PAYMENT_AMOUNT NUMBER,
PAYMENT_ON DATE,
CONSTRAINTS DEATAIL_ID_FK FOREIGN KEY(DETAIL_ID) REFERENCES TTS_STUDENTS_DETAILS(DETAIL_ID)
);



    